# Generated by Django 3.0.2 on 2020-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.BigIntegerField(unique=True),
        ),
    ]
