# Generated by Django 3.0.2 on 2020-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('photos_number', models.IntegerField()),
                ('user_number', models.IntegerField()),
                ('analysis_number', models.IntegerField()),
                ('term_months_number', models.IntegerField()),
                ('inspection_number', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user_resgister', models.IntegerField(default=0)),
            ],
        ),
    ]
