# Generated by Django 3.0.2 on 2020-04-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='inspection_number',
            field=models.IntegerField(default=0),
        ),
    ]
