# Generated by Django 3.0.2 on 2020-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_inspection_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_resgister',
            field=models.IntegerField(default=0),
        ),
    ]
