# Generated by Django 3.0.2 on 2020-05-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'permissions': (('view_dashboard', 'Can view dashboard'),)},
        ),
    ]
