# Generated by Django 3.0.5 on 2020-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='plan',
        ),
    ]
