# Generated by Django 3.0.5 on 2020-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
