# Generated by Django 3.0.2 on 2020-05-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=100)),
                ('serialnumber', models.CharField(max_length=250)),
                ('weight', models.IntegerField()),
                ('flight_time', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user_resgister', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Drone_Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('serialnumber', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=100)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.Drone')),
            ],
        ),
    ]
