# Generated by Django 3.0.2 on 2020-05-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'permissions': (('view_profile', 'Can view profile'),)},
        ),
    ]
