# Generated by Django 3.0.2 on 2020-05-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200505_1354'),
        ('pilot', '0002_auto_20200505_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilot',
            old_name='user_resgister',
            new_name='user_register',
        ),
        migrations.AddField(
            model_name='pilot',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
