# Generated by Django 3.0.2 on 2020-05-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pilot', '0003_auto_20200506_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='company',
        ),
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
